version: '3.9'

volumes:
  db:

services:
  
  api:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    command: ./api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

